Repository zarf-dev/zarf, pull requests merged in 2022-12, with the labels that each got.

#1072 Allow e2e tests to run back to back
  src/internal/packager/git/gitea.go
  src/test/e2e/30_config_file_test.go
Labels: bug

#1077 Fix SBOMs in Zarf
  src/pkg/packager/create.go
  src/pkg/packager/inspect.go
  src/test/e2e/00_use_cli_test.go
Labels: bug

#1080 Update docs for big bang core
  packages/big-bang-core/README.md
Labels: documentation

#1110 Remove all spinner.Debugf messages
  src/internal/cluster/tunnel.go
  src/internal/packager/git/clone.go
  src/internal/packager/git/pull.go
  src/internal/packager/git/push.go
  src/internal/packager/helm/chart.go
  src/pkg/message/spinner.go
  src/pkg/utils/sget.go
Labels: bug

#1111 1087 prepare find images doesnt work on local helm chart paths
  src/pkg/packager/prepare.go
  src/test/e2e/00_use_cli_test.go
Labels: bug

#1112 Fix where we are deleting tags (don't edit cache\!)
  src/internal/packager/git/fetch.go
  src/internal/packager/git/pull.go
  src/test/e2e/04_create_templating_test.go
  src/test/e2e/05_create_cache_test.go
Labels: bug

#1114 Remove zarf prefix from helm chart release names
  .github/workflows/test-upgrade.yml
  packages/gitea/zarf.yaml
  packages/logging-pgl/zarf.yaml
  packages/zarf-registry/zarf.yaml
  src/internal/packager/helm/chart.go
  src/test/e2e/25_helm_test.go
Labels: breaking-change

#1102 1091 .netrc support inside zarf itself
  .github/workflows/test-unit.yml
  CONTRIBUTING.md
  Makefile
  adr/0008-begin-using-unit-tests.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_create.md
  docs/6-developer-guide/2-testing.md
  src/cmd/initialize.go
  src/cmd/package.go
  src/cmd/tools.go
  src/config/lang/english.go
  src/internal/agent/start.go
  src/internal/packager/git/auth.go
  src/internal/packager/git/clone.go
  src/internal/packager/git/common.go
  src/internal/packager/git/fetch.go
  src/pkg/utils/auth.go
  src/pkg/utils/auth_test.go
  src/test/mocks/read_closer_mock.go
Labels: enhancement

#848 Support automatic multi-part packages based on a MaxPackageSize
  .github/codeql.yaml
  .github/workflows/scan-docs-and-schema.yml
  .gitignore
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_create.md
  examples/multi-part/zarf.yaml
  go.mod
  go.sum
  src/cmd/package.go
  src/cmd/root.go
  src/cmd/viper.go
  src/config/config.go
  src/internal/cluster/injector.go
  src/internal/cluster/tunnel.go
  src/internal/cluster/zarf.go
  src/internal/packager/validate/validate.go
  src/pkg/k8s/pods.go
  src/pkg/packager/common.go
  src/pkg/packager/create.go
  src/pkg/packager/deploy.go
  src/pkg/packager/inspect.go
  src/pkg/packager/interactive.go
  src/pkg/packager/network.go
  src/pkg/packager/remove.go
  src/pkg/utils/bytes.go
  src/pkg/utils/io.go
  src/test/e2e/05_multi_part_test.go
  src/test/e2e/30_config_file_test.go
  src/test/zarf-config-test.toml
  src/types/packager.go
  src/types/runtime.go
  src/ui/lib/api-types.ts
Labels: enhancement, packager
