Repository zarf-dev/zarf, pull requests merged in 2022-03, with the labels that each got.

#362 Pull Kubescape out of the Big Bang example
  examples/big-bang/README.md
  examples/big-bang/zarf.yaml
Labels: examples

#319 E2E test optimization for multi-distro support
  .github/workflows/slash-command-dispatch.yml
  .github/workflows/test-command.yml
  .github/workflows/test-k3d.yml
  .github/workflows/test-k3s.yml
  .github/workflows/test-kind.yml
  Makefile
  docs/adr/0002-moving-e2e-tests-away-from-terratest.md
  go.mod
  go.sum
  test/e2e/README.md
  test/e2e/common.go
  test/e2e/e2e_data_injection_test.go
  test/e2e/e2e_example_game_test.go
  test/e2e/e2e_general_cli_test.go
  test/e2e/e2e_gitea_and_grafana_test.go
  test/e2e/e2e_gitops_example_test.go
  test/e2e/main_test.go
Labels: tests, cicd, tech-debt

#346 upgrade big bang version to latest version
  .pre-commit-config.yaml
  examples/Makefile
  examples/big-bang/README.md
  examples/big-bang/kustomizations/bigbang/kustomization.yaml
  examples/big-bang/kustomizations/bigbang/values.yaml
  examples/big-bang/zarf.yaml
Labels: examples

#364 Made small update to Zarf description
  README.md
Labels: documentation

#351 #208. Basic Composability
  .github/workflows/test-k3d.yml
  .github/workflows/test-k3s.yml
  .github/workflows/test-kind.yml
  Makefile
  cli/config/config.go
  cli/internal/packager/common.go
  cli/internal/packager/compose.go
  cli/internal/packager/create.go
  cli/internal/packager/validate/validate.go
  cli/types/types.go
  docs/components.md
  examples/Makefile
  examples/composable-packages/README.md
  examples/composable-packages/zarf.yaml
  examples/flux/template/values.yaml
  examples/flux/zarf.yaml
  test/e2e/e2e_composability_test.go
Labels: enhancement, packager, needs-docs, needs-tests

#383 slightly re-arrange zarf arch diagram layout
  docs/architecture.drawio.svg
Labels: documentation

#391 Fix README NodePort Value
  README.md
Labels: documentation

#385 Composability by component
  cli/internal/packager/compose.go
  cli/types/types.go
  examples/composable-packages/zarf.yaml
  test/e2e/e2e_composability_test.go
  zarf.schema.json
Labels: packager

#398 Correct arch diagram bg color to #FFF
  docs/architecture.drawio.svg
Labels: documentation

#410 Better KUBECONFIG support
  cli/internal/k8s/common.go
Labels: enhancement

#407 Simplify cluster instantiation in tests
  .github/workflows/test-k3d.yml
  .github/workflows/test-k3s.yml
  .github/workflows/test-kind.yml
  .golangci.yml
  Makefile
  test/e2e/README.md
  test/e2e/clusters/clusters.go
  test/e2e/common.go
  test/e2e/e2e_composability_test.go
  test/e2e/e2e_example_game_test.go
  test/e2e/e2e_gitea_and_grafana_test.go
  test/e2e/e2e_gitops_example_test.go
  test/e2e/main_test.go
Labels: tests, cicd

#408 Migrate GitLab Release Pipeline to GitHub
  .github/workflows/release.yml
  .gitlab-ci.yml
  cli/.gitlab-ci.yml
Labels: cicd

#414 Fix workflow yaml for github release
  .github/workflows/release.yml
Labels: cicd

#419 fix(credentialParser): validate error before parsing password to avoid nil pointer. #418
  cli/internal/git/utils.go
Labels: possible-bug, packager

#425 Make Data Injections Happen asyc w/ Component Deployment
  cli/config/config.go
  cli/internal/packager/common.go
  cli/internal/packager/create.go
  cli/internal/packager/deploy.go
  cli/types/types.go
  examples/data-injection/manifests/data-injection.yaml
  examples/data-injection/manifests/deployment.yaml
  examples/data-injection/zarf.yaml
  test/e2e/common.go
  test/e2e/e2e_data_injection_test.go
  zarf.schema.json
Labels: bug, packager
