Repository zarf-dev/zarf, pull requests merged in 2022-10, with the labels that each got.

#846 Update 2-core-concepts.md
  docs/1-understand-the-basics.md
  docs/2-core-concepts.md
Labels: documentation, ux

#857 adds barebones terraform example
  examples/terraform/README.md
  examples/terraform/main.tf
  examples/terraform/zarf.yaml
Labels: documentation

#826 UI Typography/Layout Fixes.
  package-lock.json
  package.json
  src/config/config.go
  src/internal/api/components/list.go
  src/internal/api/start.go
  src/internal/packager/deploy.go
  src/test/ui/01_start_page.spec.ts
  src/test/ui/02_initialize_cluster.spec.ts
  src/ui/app.css
  src/ui/lib/api.ts
  src/ui/lib/components/accordion-group.svelte
  src/ui/lib/components/divider.svelte
  src/ui/lib/components/hero.svelte
  src/ui/lib/components/icon.svelte
  src/ui/lib/components/package-card.svelte
  src/ui/lib/components/package-component-accordion.svelte
  src/ui/lib/components/package-component.svelte
  src/ui/lib/components/package-details-card.svelte
  src/ui/lib/components/spinner.svelte
  src/ui/lib/components/yaml-code.svelte
  src/ui/routes/+layout.svelte
  src/ui/routes/+page.svelte
  src/ui/routes/initialize/+layout.svelte
  src/ui/routes/initialize/configure/+page.svelte
  src/ui/routes/initialize/deploy/+page.svelte
  src/ui/routes/initialize/deploy/deploy-utils.ts
  src/ui/routes/initialize/review/+page.svelte
  src/ui/routes/packages/+layout.svelte
  src/ui/routes/packages/+page.svelte
Labels: UI

#876 Switch to distribution/distribution vs regex hacking for image url pa…
  docs/4-user-guide/3-zarf-schema.md
  go.sum
  packages/zarf-registry/registry-values.yaml
  src/config/config.go
  src/injector/stage2/registry.go
  src/internal/git/utils.go
  src/internal/helm/chart.go
  src/internal/images/push.go
  src/internal/packager/create.go
  src/internal/packager/deploy.go
  src/internal/packager/injector.go
  src/internal/packager/inspect.go
  src/internal/packager/seed.go
  src/internal/utils/image.go
  src/internal/utils/yaml.go
  src/test/e2e/22_git_and_flux_test.go
  src/test/external-test/docker-registry-values.yaml
  src/types/package.go
  src/ui/lib/api-types.ts
  zarf.schema.json
  zarf.yaml
Labels: breaking-change

#861 Update 0-zarf-overview.md
  docs/0-zarf-overview.md
Labels: documentation, help wanted

#851 Update 0-set-up-and-install.md
  docs/5-operator-manual/0-set-up-and-install.md
Labels: documentation
