Repository zarf-dev/zarf, pull requests merged in 2022-07, with the labels that each got.

#578 Fix registry user in credentials output
  src/internal/packager/deploy.go
Labels: bug, packager

#587 Standardize package operations
  .github/workflows/test-k3d.yml
  .github/workflows/test-k3s.yml
  .github/workflows/test-kind.yml
  Makefile
  examples/Makefile
  examples/README.md
  examples/Vagrantfile
  examples/big-bang-umbrella/README.md
  examples/data-injection/zarf.yaml
  examples/game/README.md
  examples/istio-with-separate-cert/README.md
  examples/istio-with-separate-cert/files/bigbangdev.cert
  examples/istio-with-separate-cert/files/bigbangdev.key
  examples/istio-with-separate-cert/kustomizations/bigbang/kustomization.yaml
  examples/istio-with-separate-cert/kustomizations/bigbang/values.yaml
  examples/istio-with-separate-cert/zarf.yaml
  examples/k3d.yaml
  examples/kind.yaml
  examples/postgres-operator/Makefile
  examples/single-big-bang-package/README.md
  examples/single-big-bang-package/twistlock-zarf-connect.yaml
  examples/single-big-bang-package/zarf.yaml
  examples/tiny-kafka/charts/strimzi-values.yaml
  examples/tiny-kafka/manifests/kafka.yaml
  examples/tiny-kafka/zarf.yaml
  src/cmd/package.go
  src/cmd/prepare.go
  src/config/config.go
  src/internal/k8s/tunnel.go
  src/internal/packager/create.go
  src/internal/packager/deploy.go
  src/internal/packager/prepare.go
Labels: documentation, enhancement, examples, packager, breaking-change

#588 refactor composed package logic to handle nested composes
  src/internal/packager/compose.go
  src/internal/packager/create.go
  src/internal/packager/prepare.go
  src/internal/packager/validate/validate.go
Labels: tech-debt

#596 595 dead link on getting started site
  docs/12-support.md
  docs/3-getting-started.md
  docs/4-user-guide/1-the-zarf-cli/1-building-your-own-cli.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/0-zarf.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/2-package/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/2-package/zarf_package_create.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/2-package/zarf_package_deploy.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/2-package/zarf_package_inspect.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/archiver/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/registry/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/zarf_tools_config-schema.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/zarf_tools_get-admin-password.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/3-tools/zarf_tools_monitor.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/4-completion/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/4-completion/zarf_completion_bash.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/4-completion/zarf_completion_fish.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/4-completion/zarf_completion_powershell.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/4-completion/zarf_completion_zsh.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/5-prepare/index.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/5-prepare/zarf_prepare_find-images.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/5-prepare/zarf_prepare_patch-git.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/5-prepare/zarf_prepare_sha256sum.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_connect.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_destroy.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_init.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_version.md
  docs/4-user-guide/1-the-zarf-cli/2-cli-commond-uses.md
  docs/4-user-guide/1-the-zarf-cli/index.md
  docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
  docs/4-user-guide/2-zarf-packages/3-the-zarf-init-package.md
  docs/4-user-guide/2-zarf-packages/index.md
  docs/5-operator-manual/0-set-up-and-install.md
Labels: bug, documentation

#591 Feature: Add only filters for local OS and cluster architecture component filtering
  .tool-versions
  docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
  docs/4-user-guide/2-zarf-packages/2-zarf-components.md
  go.mod
  go.sum
  packages/big-bang-core/zarf.yaml
  packages/distros/k3s/common/empty-file
  packages/distros/k3s/common/k3s.service
  packages/distros/k3s/common/zarf-clean-k3s.sh
  packages/distros/k3s/common/zarf.yaml
  packages/distros/k3s/zarf.yaml
  src/config/config.go
  src/internal/packager/common.go
  src/internal/packager/compose.go
  src/internal/packager/create.go
  src/internal/packager/deploy.go
  src/internal/packager/inspect.go
  src/internal/packager/prepare.go
  src/test/e2e/zarf.yaml
  src/types/component.go
  src/types/package.go
  zarf.schema.json
Labels: enhancement, packager

#623 fixes link in docs
  docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
Labels: documentation

#628 Gracefully handle zarf shorthand removal
  src/cmd/root.go
Labels: enhancement, packager

#511 Debug Message Cleanup
  src/cmd/destroy.go
  src/config/secret.go
  src/internal/agent/hooks/pods.go
  src/internal/agent/http/handlers.go
  src/internal/agent/http/server.go
  src/internal/agent/operations/hook.go
  src/internal/git/push.go
  src/internal/git/utils.go
  src/internal/images/push.go
  src/internal/k8s/common.go
  src/internal/k8s/configmap.go
  src/internal/k8s/namespace.go
  src/internal/k8s/secrets.go
  src/internal/k8s/services.go
  src/internal/k8s/state.go
  src/internal/k8s/zarf.go
  src/internal/message/message.go
  src/internal/packager/components.go
  src/internal/packager/injector.go
  src/internal/packager/seed.go
  src/internal/template/template.go
  src/test/e2e/main_test.go
Labels: tech-debt

#644 Data injection stability improvements
  docs/4-user-guide/3-zarf-schema.md
  examples/data-injection/manifest.yaml
  examples/data-injection/zarf.yaml
  go.sum
  src/config/config.go
  src/internal/helm/chart.go
  src/internal/k8s/pods.go
  src/internal/packager/data.go
  src/internal/packager/deploy.go
  src/internal/template/template.go
  src/test/e2e/23_data_injection_test.go
  src/types/component.go
  zarf.schema.json
Labels: bug, tests, packager, breaking-change

#647 change from kubectl exec -> kubectl logs for data injection test
  src/test/e2e/23_data_injection_test.go
Labels: tests
