Repository zarf-dev/zarf, pull requests merged in 2022-06, with the labels that each got.

#500 Add insecure flag to zarf package create
  src/cmd/package.go
  src/cmd/tools.go
  src/config/config.go
  src/internal/images/copy.go
  src/internal/images/pull.go
  src/internal/images/push.go
  src/internal/packager/injector.go
  src/internal/packager/prepare.go
  src/internal/sbom/catalog.go
  src/types/types.go
Labels: packager

#498 Use GoReleaser for GitHub release workflow
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  README.md
  src/cmd/initialize.go
  src/internal/utils/io.go
Labels: cicd

#506 Add init package downloader
  src/cmd/initialize.go
  src/config/config.go
  src/internal/utils/github.go
Labels: enhancement, packager

#508 fix kustomize path for big-bang core package
  packages/big-bang-core/kustomization/core-light/kustomization.yaml
Labels: bug, examples

#510 Injector stability improvements
  src/internal/k8s/images.go
  src/internal/packager/injector.go
Labels: bug, cloud-distro, injector

#550 Add support for package deploy via cosign sget
  .hooks/verify-zarf-schema.sh
  Makefile
  main.go
  src/cmd/package.go
  src/config/config.go
  src/internal/packager/common.go
  src/main.go
  src/test/e2e/e2e_remote_sget_test.go
  src/types/types.go
Labels: enhancement, packager

#567 Update goreleaser build path
  .goreleaser.yaml
Labels: cicd, tech-debt
