Repository zarf-dev/zarf, pull requests merged in 2023-03, with the labels that each got.

#1403 Content and style updates to docs overview
  docs/0-zarf-overview.md
Labels: documentation, Content

#1394 Content edits to Docs Overview
  docs/0-zarf-overview.md
Labels: documentation, marketing

#1485 Docs edits for "Understand the Basics"
  docs/1-understand-the-basics.md
Labels: documentation

#1480 Potential fix for helm not rolling back properly
  examples/config-file/simple-configmap.yaml
  src/internal/packager/helm/chart.go
  src/test/e2e/25_helm_test.go
  src/test/e2e/30_config_file_test.go
  src/test/test-packages/25-evil-dos-games/manifests/deployment.yaml
  src/test/test-packages/25-evil-dos-games/manifests/evil-service.yaml
  src/test/test-packages/25-evil-dos-games/zarf.yaml
Labels: jackal

#1508 Docs edits to "Getting Started" page
  docs/3-getting-started.md
Labels: documentation

#1512 Docs edits to User Guide page
  docs/4-user-guide/index.md
Labels: documentation

#1519 Docs edits to "The Zarf CLI" page
  docs/4-user-guide/1-the-zarf-cli/index.md
Labels: documentation

#1528 Docs edits for "Building Your Own Zarf CLI" page
  docs/4-user-guide/1-the-zarf-cli/1-building-your-own-cli.md
Labels: documentation

#1533 Docs updates to "Common CLI Uses" page
  docs/4-user-guide/1-the-zarf-cli/2-cli-common-uses.md
Labels: documentation
