Repository zarf-dev/zarf, pull requests merged in 2023-04, with the labels that each got.

#1544 Docs edits for "Zarf Packages" page
  docs/4-user-guide/2-zarf-packages/index.md
Labels: documentation

#1548 docs edits to "Understanding Zarf Packages" page
  docs/4-user-guide/2-zarf-packages/1-zarf-packages.md
Labels: documentation

#1586 Add style guide page and copy
  docs/6-developer-guide/4-style-guide.md
Labels: documentation

#1602 Update --confirm flag description for init and package deploy cmd
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_init.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_deploy.md
  src/config/lang/english.go
Labels: ux, developer-experience

#1605 Docs edits to "Code Testing" page
  docs/6-developer-guide/2-testing.md
Labels: documentation

#1590 Switch to per-image tunnels, CRC on tags, and progressbar for image pushes
  packages/distros/k3s/common/zarf.yaml
  packages/zarf-registry/chart/templates/hpa.yaml
  src/cmd/connect.go
  src/cmd/destroy.go
  src/cmd/package.go
  src/config/config.go
  src/internal/api/cluster/cluster.go
  src/internal/cluster/common.go
  src/internal/cluster/state.go
  src/internal/cluster/tunnel.go
  src/internal/cluster/zarf.go
  src/internal/packager/images/pull.go
  src/internal/packager/images/push.go
  src/pkg/message/message.go
  src/pkg/message/progress.go
  src/pkg/packager/components.go
  src/pkg/packager/deploy.go
  src/pkg/packager/deprecated/common.go
  src/pkg/packager/interactive.go
  src/pkg/packager/remove.go
  src/pkg/transform/image.go
  src/pkg/transform/image_test.go
  src/pkg/utils/network.go
  src/pkg/utils/yaml.go
  src/test/e2e/20_zarf_init_test.go
  src/test/e2e/21_connect_test.go
  src/test/ui/02_initialize_cluster.spec.ts
Labels: jackal

#1634 IA: Renaming Developer Guide to Contribute to Zarf
  CONTRIBUTING.md
  README.md
  docs/0-zarf-overview.md
  docs/13-walkthroughs/0-using-zarf-package-create.md
  docs/4-user-guide/index.md
  docs/6-contribute-to-zarf/1-contributor-guide.md
  docs/6-contribute-to-zarf/2-testing.md
  docs/6-contribute-to-zarf/3-nerd-notes.md
  docs/6-contribute-to-zarf/4-style-guide.md
  docs/6-contribute-to-zarf/_category_.json
  docs/6-developer-guide/_category_.json
Labels: documentation

#1597 Docs updated to "Set Up and Install" page
  docs/5-operator-manual/0-set-up-and-install.md
Labels: documentation
