Repository zarf-dev/zarf, pull requests merged in 2023-01, with the labels that each got.

#1169 1057 cleanup master branch refs -> update to use "main" in docs
  docs/4-user-guide/2-zarf-packages/3-the-zarf-init-package.md
  docs/4-user-guide/3-zarf-schema.md
  docs/4-user-guide/4-vscode.md
  docs/6-developer-guide/3-nerd-notes.md
  hack/zarf-jsfh-template/base.md
Labels: documentation

#1174 Update UI Theme
  src/ui/app.css
  src/ui/lib/components/header.svelte
  src/ui/lib/components/theme-toggle.svelte
  src/ui/lib/palette.ts
  src/ui/lib/store.ts
  src/ui/routes/+layout.svelte
Labels: UI

#1197 Made show all namespace default for k9 dash
  src/cmd/tools.go
Labels: enhancement

#1230 Fix external registry issues
  src/cmd/tools.go
  src/config/config.go
  src/config/lang/english.go
  src/internal/agent/hooks/pods.go
  src/internal/agent/start.go
  src/internal/cluster/injector.go
  src/internal/cluster/secrets.go
  src/internal/cluster/seed.go
  src/internal/cluster/tunnel.go
  src/internal/packager/git/gitea.go
  src/internal/packager/images/push.go
  src/internal/packager/template/template.go
  src/pkg/k8s/services.go
  src/pkg/packager/deploy.go
  src/test/e2e/20_zarf_init_test.go
  src/test/external-test/common.go
  src/test/external-test/configure-gitea.sh
  src/test/external-test/docker-compose.yml
  src/test/external-test/ext_in_cluster_init_test.go
  src/test/external-test/ext_out_cluster_init_test.go
  src/test/external-test/secret.yaml
Labels: jackal

#1265 UI Package Deploy Routing Refactor
  src/internal/api/packages/find.go
  src/internal/api/packages/read.go
  src/test/ui/01_start_page.spec.ts
  src/test/ui/02_initialize_cluster.spec.ts
  src/ui/lib/components/package-component-accordion.svelte
  src/ui/lib/components/package-err-not-found.svelte
  src/ui/lib/components/spinner.svelte
  src/ui/lib/components/yaml-code.svelte
  src/ui/lib/typography.ts
  src/ui/routes/+error.svelte
  src/ui/routes/+page.svelte
  src/ui/routes/initialize/+layout.svelte
  src/ui/routes/package/[name]/+layout.svelte
  src/ui/routes/package/[name]/configure/+page.svelte
  src/ui/routes/package/[name]/deploy/+page.svelte
  src/ui/routes/package/[name]/deploy/deploy-utils.ts
  src/ui/routes/package/[name]/finished/+page.svelte
  src/ui/routes/package/[name]/review/+page.svelte
  src/ui/routes/package/deploy/+page.svelte
  src/ui/routes/packages/+page.svelte
Labels: ux, UI
