Repository zarf-dev/zarf, pull requests merged in 2023-02, with the labels that each got.

#1154 Update value of localPath for composable packages
  packages/zarf-registry/zarf.yaml
  src/pkg/packager/compose.go
Labels: external-contributor

#1314 Update FAQ - Add license information
  docs/9-faq.md
Labels: documentation, ux

#1280 add common insecure flag
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_completion.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_completion_bash.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_completion_fish.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_completion_powershell.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_completion_zsh.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_connect.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_connect_list.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_destroy.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_init.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_create.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_deploy.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_inspect.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_list.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_remove.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare_find-images.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare_generate-config.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare_patch-git.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare_sha256sum.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver_compress.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_archiver_decompress.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_clear-cache.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_gen-pki.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_get-creds.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_monitor.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_catalog.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_copy.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_login.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_pull.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_push.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom_attest.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom_convert.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom_login.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom_packages.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_sbom_version.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_version.md
  src/cmd/package.go
  src/cmd/root.go
  src/cmd/viper.go
  src/config/config.go
  src/config/lang/english.go
  src/internal/packager/images/push.go
  src/pkg/packager/create.go
  src/pkg/packager/deploy.go
  src/pkg/packager/network.go
  src/pkg/packager/prepare.go
  src/test/e2e/30_config_file_test.go
  src/test/zarf-config-test.toml
  src/types/runtime.go
  src/ui/lib/api-types.ts
Labels: external-contributor

#1338 Merge Jeff+Wayne action ideas
  examples/component-actions/zarf.yaml
  src/pkg/message/spinner.go
  src/pkg/packager/actions.go
  src/pkg/utils/exec/exec.go
Labels: jackal

#1332 Better Docker Daemon Support + Cleaner Actions Terminal Output
  adr/0012-local-image-support-via-docker.md
  docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_package_create.md
  docs/4-user-guide/3-zarf-schema.md
  docs/9-faq.md
  examples/component-actions/zarf.yaml
  go.mod
  go.sum
  src/cmd/package.go
  src/cmd/viper.go
  src/internal/packager/git/clone.go
  src/internal/packager/git/fetch.go
  src/internal/packager/git/pull.go
  src/internal/packager/helm/repo.go
  src/internal/packager/images/common.go
  src/internal/packager/images/pull.go
  src/internal/packager/sbom/catalog.go
  src/internal/packager/sbom/viewer.go
  src/pkg/message/spinner.go
  src/pkg/packager/actions.go
  src/pkg/packager/create.go
  src/pkg/packager/deploy.go
  src/pkg/packager/variables.go
  src/pkg/utils/exec/exec.go
  src/test/e2e/02_component_actions_test.go
  src/types/component.go
  src/types/runtime.go
  src/ui/lib/api-types.ts
  zarf.schema.json
Labels: jackal

#1240 Updated push.go
  src/internal/packager/git/push.go
Labels: external-contributor

#1386 Docs: fixed broken links
  docs/1-understand-the-basics.md
Labels: documentation
