Repository zarf-dev/zarf, pull requests merged in 2024-05, with the labels that each got.

#2456 fix!: do not uninstall helm chart after failed install or upgrade
  site/src/content/docs/ref/deploy.mdx
  src/internal/packager/helm/chart.go
  src/pkg/packager/deploy.go
  src/test/e2e/25_helm_test.go
  src/test/e2e/36_custom_retries_test.go
Labels: breaking-change 💔

#2419 refactor: move validate to expose it as receivers
  src/internal/packager/validate/validate.go
  src/pkg/packager/composer/list.go
  src/pkg/packager/create.go
  src/pkg/packager/dev.go
  src/pkg/packager/filters/deploy.go
  src/pkg/packager/filters/os_test.go
  src/pkg/packager/filters/utils.go
  src/pkg/packager/generate.go
  src/pkg/packager/sources/cluster.go
  src/pkg/variables/types.go
  src/types/component.go
  src/types/validate.go
Labels: ready-for-review

#2488 docs: add additional detail to security policy
  .github/SECURITY.md
Labels: documentation 📘, community

#2405 refactor: context usage in k8s code
  .pre-commit-config.yaml
  src/cmd/common/utils.go
  src/cmd/connect.go
  src/cmd/destroy.go
  src/cmd/dev.go
  src/cmd/initialize.go
  src/cmd/internal.go
  src/cmd/package.go
  src/cmd/root.go
  src/cmd/tools/archiver.go
  src/cmd/tools/crane.go
  src/cmd/tools/helm/load_plugins.go
  src/cmd/tools/helm/repo_add.go
  src/cmd/tools/helm/repo_index.go
  src/cmd/tools/zarf.go
  src/extensions/bigbang/test/bigbang_test.go
  src/internal/packager/git/gitea.go
  src/internal/packager/helm/post-render.go
  src/internal/packager/helm/zarf.go
  src/internal/packager/images/push.go
  src/pkg/cluster/common.go
  src/pkg/cluster/data.go
  src/pkg/cluster/injector.go
  src/pkg/cluster/namespace.go
  src/pkg/cluster/secrets.go
  src/pkg/cluster/state.go
  src/pkg/cluster/tunnel.go
  src/pkg/cluster/zarf.go
  src/pkg/k8s/common.go
  src/pkg/k8s/configmap.go
  src/pkg/k8s/dynamic.go
  src/pkg/k8s/hpa.go
  src/pkg/k8s/info.go
  src/pkg/k8s/namespace.go
  src/pkg/k8s/nodes.go
  src/pkg/k8s/pods.go
  src/pkg/k8s/sa.go
  src/pkg/k8s/secrets.go
  src/pkg/k8s/services.go
  src/pkg/k8s/tunnel.go
  src/pkg/packager/common.go
  src/pkg/packager/common_test.go
  src/pkg/packager/deploy.go
  src/pkg/packager/dev.go
  src/pkg/packager/mirror.go
  src/pkg/packager/remove.go
  src/pkg/packager/sources/cluster.go
  src/test/e2e/21_connect_creds_test.go
  src/test/e2e/22_git_and_gitops_test.go
  src/test/e2e/23_data_injection_test.go
  src/test/e2e/26_simple_packages_test.go
  src/test/e2e/30_config_file_test.go
  src/test/e2e/33_component_webhooks_test.go
  src/test/e2e/99_yolo_test.go
  src/test/external/ext_in_cluster_test.go
  src/test/external/ext_out_cluster_test.go
Labels: tech-debt 💳, breaking-change 💔, openssf, ready-for-review

#2518 fix(agent): missing path for pod without labels
  src/internal/agent/hooks/pods.go
  src/test/e2e/37_pod_without_labels_test.go
  src/test/packages/37-pod-without-labels/pod.yaml
Labels: bug 🐞

#2563 test: remove validate pkg arch e2e test
  src/pkg/packager/common_test.go
  src/test/e2e/29_mismatched_checks_test.go
Labels: ready-for-review

#2564 test: remove TestMismatchedVersions e2e test
  src/pkg/message/message.go
  src/pkg/packager/common.go
  src/pkg/packager/deprecated/common.go
  src/pkg/packager/deprecated/common_test.go
  src/test/e2e/29_config_file_test.go
  src/test/e2e/29_mismatched_checks_test.go
  src/test/e2e/30_component_action_cluster_test.go
  src/test/e2e/31_checksum_and_signature_test.go
  src/test/e2e/32_component_webhooks_test.go
  src/test/e2e/33_manifest_with_symlink_test.go
  src/test/e2e/34_custom_init_package_test.go
  src/test/e2e/35_custom_retries_test.go
  src/test/e2e/36_pod_without_labels_test.go
Labels: ready-for-review
