Repository zarf-dev/zarf, pull requests merged in 2025-05, with the labels that each got.

#3732 fix: resolve CVE-2025-3445 in cmd/archiver with pkg/archive
  go.mod
  go.sum
  src/cmd/archiver.go
  src/cmd/dev.go
  src/internal/packager2/layout/create.go
  src/internal/packager2/layout/import.go
  src/internal/packager2/layout/package.go
  src/internal/packager2/layout/sbom.go
  src/internal/packager2/pull.go
  src/pkg/archive/archive.go
  src/pkg/archive/archive_test.go
  src/pkg/cluster/injector.go
  src/pkg/layout/component.go
  src/pkg/packager/composer/oci.go
  src/pkg/packager/creator/normal.go
  src/pkg/packager/creator/skeleton.go
  src/pkg/packager/sources/oci.go
  src/pkg/packager/sources/tarball.go
  src/pkg/packager/sources/utils.go
  src/test/e2e/08_create_differential_test.go
Labels: bug 🐞, dependencies, project-hygiene

#3771 chore(dependencies): update crane
  go.mod
  go.sum
Labels: dependencies

#3823 chore(sustainability): document the release process
  RELEASES.md
Labels: documentation 📘

#3846 feat(utils): support user interrupts in utils.ExecuteWait and add debug logging
  src/pkg/utils/wait.go
Labels: ux, project-hygiene

#3848 feat(utils): add user interrupts to wait-for on network protocols
  src/pkg/utils/wait.go
Labels: ux, project-hygiene
